version: '3.5'
services:
  app:
    ports:
      - "3001:3001"
    networks:
      - openstax
    secrets:
      - hypothesis
    environment:
      - RAILS_ENV=test
      - ASSETS_URL=https://tutor-assets.sandbox.openstax.org
      - HYPOTHESIS_HOST=hypothesis.sandbox.openstax.org
      - HYPOTHESIS_APP_URL=https://hypothesis.sandbox.openstax.org
      - HYPOTHESIS_API_URL=https://hypothesis.sandbox.openstax.org/api/
      - REDIS_URL=redis://redis:6379/0
      - OXT_DB_HOST=postgres95
networks:
  openstax:
    external:
      name: openstax
secrets:
  hypothesis:
    external: true
